#!/bin/bash
#
# Scans Submissions/ for ClipExperience conformances and generates SubmissionRegistry.swift.
# Added as an Xcode Run Script Build Phase so the registry updates every build.

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SUBMISSIONS_DIR="$ROOT_DIR/Submissions"
OUTPUT_FILE="$ROOT_DIR/ReactivChallengeKit/ReactivChallengeKit/SubmissionRegistry.swift"
OUTPUT_SOURCES_FILE="$ROOT_DIR/ReactivChallengeKit/ReactivChallengeKit/GeneratedSubmissions.swift"

TYPES=()
SOURCE_FILES=()
TEAM_DIRS=()

if [ -d "$SUBMISSIONS_DIR" ]; then
    while IFS= read -r team_dir; do
        if [ -n "$team_dir" ]; then
            TEAM_DIRS+=("$team_dir")
        fi
    done < <(find "$SUBMISSIONS_DIR" -mindepth 1 -maxdepth 1 -type d ! -name "_*" 2>/dev/null || true)

    for team_dir in "${TEAM_DIRS[@]}"; do
    while IFS= read -r line; do
        type_name="$(echo "$line" | sed -E 's/.*struct[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*:.*/\1/')"
        if [ -n "$type_name" ]; then
            TYPES+=("$type_name")
        fi
    done < <(
        grep -r \
            --include="*.swift" \
            'struct[[:space:]]\+[A-Za-z0-9_]*[[:space:]]*:.*ClipExperience' \
            "$team_dir" 2>/dev/null || true
    )
    done

    for team_dir in "${TEAM_DIRS[@]}"; do
        while IFS= read -r swift_file; do
            if [ -n "$swift_file" ]; then
                SOURCE_FILES+=("$swift_file")
            fi
        done < <(find "$team_dir" -type f -name "*.swift" 2>/dev/null || true)
    done
fi

# Keep deterministic output order and avoid duplicate entries.
if [ "${#TYPES[@]}" -gt 0 ]; then
    TYPES_SORTED=()
    while IFS= read -r type_name; do
        if [ -n "$type_name" ]; then
            TYPES_SORTED+=("$type_name")
        fi
    done < <(printf "%s\n" "${TYPES[@]}" | sort -u)
    TYPES=("${TYPES_SORTED[@]}")
fi
if [ "${#SOURCE_FILES[@]}" -gt 0 ]; then
    SOURCE_FILES_SORTED=()
    while IFS= read -r source_file; do
        if [ -n "$source_file" ]; then
            SOURCE_FILES_SORTED+=("$source_file")
        fi
    done < <(printf "%s\n" "${SOURCE_FILES[@]}" | sort -u)
    SOURCE_FILES=("${SOURCE_FILES_SORTED[@]}")
fi

{
    echo "//  SubmissionRegistry.swift"
    echo "//  ReactivChallengeKit"
    echo "//"
    echo "//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved."
    echo "//"
    echo ""
    echo "/// Auto-generated by scripts/generate-registry.sh — do not edit manually."
    echo "enum SubmissionRegistry {"
    echo "    static let all: [any ClipExperience.Type] = ["

    if [ "${#TYPES[@]}" -gt 0 ]; then
        for type in "${TYPES[@]}"; do
            echo "        ${type}.self,"
        done
    fi

    echo "    ]"
    echo "}"
} > "$OUTPUT_FILE"

{
    echo "//  GeneratedSubmissions.swift"
    echo "//  ReactivChallengeKit"
    echo "//"
    echo "//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved."
    echo "//"
    echo ""
    echo "/// Auto-generated by scripts/generate-registry.sh — do not edit manually."
    echo ""

    if [ "${#SOURCE_FILES[@]}" -gt 0 ]; then
        for source_file in "${SOURCE_FILES[@]}"; do
            echo "// MARK: - From ${source_file#$ROOT_DIR/}"
            echo ""
            cat "$source_file"
            echo ""
        done
    else
        echo "// No submissions discovered."
    fi
} > "$OUTPUT_SOURCES_FILE"

echo "SubmissionRegistry: found ${#TYPES[@]} submission(s), ${#SOURCE_FILES[@]} source file(s)"
