//  GeneratedSubmissions.swift
//  ReactivChallengeKit
//
//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved.
//

/// Auto-generated by scripts/generate-registry.sh — do not edit manually.

// MARK: - From Submissions/deedscan/DeedScanClipExperience.swift

//  DeedScanClipExperience.swift
//  ReactivChallengeKit
//
//  DeedScan App Clip: No-commission Canadian real estate marketplace.
//  Scan QR on for-sale sign → instant property view → message seller or view full listing.

import SwiftUI
import UIKit

// MARK: - API Models

private struct ListingResponse: Codable {
    let id: String
    let title: String
    let description: String?
    let address: String
    let price: Int
    let imageUrl: String?
    let sqft: Int?
    let bedrooms: Int?
    let bathrooms: Int?
    let confidenceScore: Int?
    let latitude: Double?
    let longitude: Double?
    let photos: [PhotoResponse]?
    let seller: SellerResponse?
}

private struct PhotoResponse: Codable {
    let id: String
    let url: String
    let order: Int
}

private struct SellerResponse: Codable {
    let id: String
    let name: String?
}

private struct NearbyListingsResponse: Codable {
    let listings: [ListingResponse]?
}

// MARK: - Helpers

private func formatPrice(_ cents: Int) -> String? {
    let formatter = NumberFormatter()
    formatter.numberStyle = .currency
    formatter.currencyCode = "CAD"
    formatter.maximumFractionDigits = 0
    return formatter.string(from: NSNumber(value: cents))
}

// MARK: - DeedScan Clip Experience

struct DeedScanClipExperience: ClipExperience {
    /// Matches deedscan.app/clip/:id — tap the card or type deedscan.app/clip/demo_listing_001
    static let urlPattern = "deedscan.app/clip/:id"
    static let clipName = "DeedScan Property View"
    static let clipDescription = "Scan a for-sale sign QR to view the property and message the seller instantly."
    static let teamName = "DeedScan"
    static let touchpoint: JourneyTouchpoint = .onSite
    static let invocationSource: InvocationSource = .qrCode

    let context: ClipContext

    @State private var listing: ListingResponse?
    @State private var nearbyListings: [ListingResponse] = []
    @State private var isLoading = true
    @State private var errorMessage: String?
    @State private var photoIndex = 0

    private var listingId: String {
        context.pathParameters["id"] ?? context.queryParameters["id"] ?? ""
    }

    /// URL path/query gives the listing id. Backend expects demo IDs (e.g. demo_listing_001).
    /// The lab's default sample URL uses id "42"; we map that to demo_listing_001 so the clip works
    /// when opened from the On-Site card without requiring changes outside this submission.
    private var apiListingId: String {
        let id = listingId
        return id.isEmpty ? "" : (id == "42" ? "demo_listing_001" : id)
    }

    /// Local dev: backend + Auth0 are configured for http://localhost:3000 on your Mac.
    /// The simulator can talk to your Mac via localhost, so we use that host for both API calls
    /// and deep links (message seller, view full listing).
    private var apiBaseURL: String { "http://localhost:3000" }
    private var webBaseURL: String { "http://localhost:3000" }

    var body: some View {
        ZStack {
            ClipBackground()

            ScrollView {
                VStack(spacing: 16) {
                    if isLoading {
                        loadingView
                    } else if let error = errorMessage {
                        errorView(message: error)
                    } else if let listing = listing {
                        propertyDetailView(listing: listing)
                        if !nearbyListings.isEmpty {
                            findSimilarSection
                        }
                    }
                }
                .padding(.bottom, 24)
            }
            .scrollIndicators(.hidden)
            .task {
                await loadListing()
            }
        }
    }

    // MARK: - Loading

    private var loadingView: some View {
        VStack(spacing: 20) {
            Spacer(minLength: 60)
            ProgressView()
                .scaleEffect(1.2)
            Text("Loading property…")
                .font(.system(size: 15))
                .foregroundStyle(.secondary)
            Spacer(minLength: 60)
        }
        .frame(maxWidth: .infinity)
    }

    private func errorView(message: String) -> some View {
        VStack(spacing: 20) {
            Spacer(minLength: 40)
            Image(systemName: "exclamationmark.triangle.fill")
                .font(.system(size: 48))
                .foregroundStyle(.orange)
            Text(message)
                .font(.system(size: 15))
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 24)
            if !listingId.isEmpty {
                ClipActionButton(title: "Retry", icon: "arrow.clockwise") {
                    Task { await loadListing() }
                }
                .padding(.horizontal, 24)
            }
            Spacer(minLength: 40)
        }
    }

    // MARK: - Property Detail

    private func propertyDetailView(listing: ListingResponse) -> some View {
        VStack(spacing: 16) {
            photoGallery(listing: listing)
            propertyInfo(listing: listing)
            ctaButtons(listing: listing)
        }
        .padding(.horizontal, 16)
        .padding(.top, 8)
    }

    private func photoGallery(listing: ListingResponse) -> some View {
        let photoURLs = (listing.photos?.sorted { $0.order < $1.order }.map { $0.url } ?? [])
            + (listing.imageUrl.map { [$0] } ?? [])
        let urls = photoURLs.isEmpty ? [] : photoURLs

        return Group {
            if urls.isEmpty {
                ZStack {
                    RoundedRectangle(cornerRadius: 16)
                        .fill(Color(.tertiarySystemFill))
                        .aspectRatio(4/3, contentMode: .fit)
                    Image(systemName: "house.fill")
                        .font(.system(size: 48))
                        .foregroundStyle(.tertiary)
                }
            } else {
                TabView(selection: $photoIndex) {
                    ForEach(Array(urls.enumerated()), id: \.offset) { index, urlString in
                        if let url = URL(string: urlString) {
                            AsyncImage(url: url) { phase in
                                switch phase {
                                case .success(let image):
                                    image
                                        .resizable()
                                        .scaledToFill()
                                case .failure:
                                    Image(systemName: "photo")
                                        .font(.largeTitle)
                                        .foregroundStyle(.tertiary)
                                default:
                                    ProgressView()
                                }
                            }
                            .frame(height: 220)
                            .clipped()
                            .tag(index)
                        }
                    }
                }
                .tabViewStyle(.page(indexDisplayMode: urls.count > 1 ? .automatic : .never))
                .frame(height: 220)
                .clipShape(RoundedRectangle(cornerRadius: 16))
            }
        }
    }

    private func propertyInfo(listing: ListingResponse) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .top) {
                VStack(alignment: .leading, spacing: 4) {
                    Text(listing.title)
                        .font(.system(size: 20, weight: .bold))
                        .foregroundStyle(.primary)
                    if !listing.address.isEmpty {
                        Label(listing.address, systemImage: "mappin.circle.fill")
                            .font(.system(size: 14))
                            .foregroundStyle(.secondary)
                    }
                }
                Spacer()
                confidenceBadge(score: listing.confidenceScore)
            }

            HStack(spacing: 16) {
                if let price = formatPrice(listing.price) {
                    Label(price, systemImage: "dollarsign.circle.fill")
                        .font(.system(size: 18, weight: .semibold))
                        .foregroundStyle(.primary)
                }
                if let beds = listing.bedrooms {
                    Label("\(beds) bed", systemImage: "bed.double.fill")
                        .font(.system(size: 14))
                        .foregroundStyle(.secondary)
                }
                Label("\(listing.bathrooms ?? 3) bath", systemImage: "shower.fill")
                    .font(.system(size: 14))
                    .foregroundStyle(.secondary)
                if let sqft = listing.sqft {
                    Label("\(sqft) sqft", systemImage: "square.dashed")
                        .font(.system(size: 14))
                        .foregroundStyle(.secondary)
                }
            }

            if let desc = listing.description, !desc.isEmpty {
                Text(desc)
                    .font(.system(size: 14))
                    .foregroundStyle(.secondary)
                    .lineLimit(3)
            }
        }
        .padding(16)
        .glassEffect(.regular.interactive(), in: RoundedRectangle(cornerRadius: 16))
    }

    private func confidenceBadge(score: Int?) -> some View {
        let (label, color) = confidenceLabelAndColor(score: score)
        return Text(label)
            .font(.system(size: 11, weight: .semibold))
            .foregroundStyle(.white)
            .padding(.horizontal, 10)
            .padding(.vertical, 5)
            .background(color, in: RoundedRectangle(cornerRadius: 8))
    }

    private func confidenceLabelAndColor(score: Int?) -> (String, Color) {
        guard let s = score else { return ("Pending", .orange) }
        if s >= 85 { return ("Verified", .green) }
        if s >= 60 { return ("Pending", .orange) }
        return ("Low", .red)
    }

    // MARK: - CTAs

    private func ctaButtons(listing: ListingResponse) -> some View {
        VStack(spacing: 10) {
            ClipActionButton(
                title: "Message Seller",
                icon: "message.fill"
            ) {
                openURL("\(webBaseURL)/messages?listingId=\(listing.id)&otherUserId=\(listing.seller?.id ?? "")")
            }

            ClipActionButton(
                title: "View Full Listing",
                icon: "safari",
                style: .secondary
            ) {
                openURL("\(webBaseURL)/listings/\(listing.id)")
            }
        }
    }

    private func openURL(_ urlString: String) {
        guard let url = URL(string: urlString) else { return }
        #if canImport(UIKit)
        UIApplication.shared.open(url)
        #endif
    }

    // MARK: - Find Similar

    private var findSimilarSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("More nearby")
                .font(.system(size: 17, weight: .semibold))
                .foregroundStyle(.primary)

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 12) {
                    ForEach(nearbyListings.prefix(5), id: \.id) { item in
                        PropertyCardView(listing: item) {
                            listing = item
                            if let lat = item.latitude, let lng = item.longitude {
                                Task { await loadNearby(lat: lat, lng: lng, excludeId: item.id) }
                            }
                        }
                    }
                }
            }
        }
        .padding(.horizontal, 16)
    }

    // MARK: - API

    private func loadListing() async {
        let id = apiListingId
        guard !id.isEmpty else {
            errorMessage = "No listing ID. Tap the card or type deedscan.app/clip/demo_listing_001"
            isLoading = false
            return
        }

        isLoading = true
        errorMessage = nil

        guard let url = URL(string: "\(apiBaseURL)/api/listings/\(id)") else {
            errorMessage = "Invalid API URL"
            isLoading = false
            return
        }

        var request = URLRequest(url: url)
        request.timeoutInterval = 15

        do {
            let (data, response) = try await URLSession.shared.data(for: request)
            guard let http = response as? HTTPURLResponse else {
                errorMessage = "Invalid response"
                isLoading = false
                return
            }
            guard http.statusCode == 200 else {
                errorMessage = "Property not found (HTTP \(http.statusCode))"
                isLoading = false
                return
            }
            let decoded = try JSONDecoder().decode(ListingResponse.self, from: data)
            let lat = decoded.latitude
            let lng = decoded.longitude
            let excludeId = decoded.id
            await MainActor.run {
                listing = decoded
                isLoading = false
            }
            if let lat = lat, let lng = lng {
                await loadNearby(lat: lat, lng: lng, excludeId: excludeId)
            }
        } catch {
            await MainActor.run {
                #if DEBUG
                errorMessage = "Could not load property: \(error.localizedDescription)"
                #else
                errorMessage = "Could not load property. Is the backend running?"
                #endif
                isLoading = false
            }
        }
    }

    private func loadNearby(lat: Double, lng: Double, excludeId: String) async {
        guard var components = URLComponents(string: "\(apiBaseURL)/api/listings/nearby") else { return }
        components.queryItems = [
            URLQueryItem(name: "lat", value: String(lat)),
            URLQueryItem(name: "lng", value: String(lng)),
            URLQueryItem(name: "radius_km", value: "5")
        ]
        guard let url = components.url else { return }

        var request = URLRequest(url: url)
        request.timeoutInterval = 15

        do {
            let (data, _) = try await URLSession.shared.data(for: request)
            var items: [ListingResponse] = []
            if let arr = try? JSONDecoder().decode([ListingResponse].self, from: data) {
                items = arr
            } else if let decoded = try? JSONDecoder().decode(NearbyListingsResponse.self, from: data) {
                items = decoded.listings ?? []
            }
            await MainActor.run {
                nearbyListings = items.filter { $0.id != excludeId }
            }
        } catch {
            await MainActor.run { nearbyListings = [] }
        }
    }
}

// MARK: - Property Card

private struct PropertyCardView: View {
    let listing: ListingResponse
    let onTap: () -> Void

    private var imageURL: String? {
        listing.photos?.sorted { $0.order < $1.order }.first?.url ?? listing.imageUrl
    }

    var body: some View {
        Button(action: onTap) {
            VStack(alignment: .leading, spacing: 8) {
                Group {
                    if let urlString = imageURL, let url = URL(string: urlString) {
                        AsyncImage(url: url) { phase in
                            switch phase {
                            case .success(let img): img.resizable().scaledToFill()
                            default: Color(.tertiarySystemFill)
                            }
                        }
                    } else {
                        Color(.tertiarySystemFill)
                    }
                }
                .frame(width: 140, height: 100)
                .clipped()
                .clipShape(RoundedRectangle(cornerRadius: 12))

                Text(listing.title)
                    .font(.system(size: 13, weight: .semibold))
                    .lineLimit(2)
                    .foregroundStyle(.primary)
                if let price = formatPrice(listing.price) {
                    Text(price)
                        .font(.system(size: 12))
                        .foregroundStyle(.secondary)
                }
            }
            .frame(width: 140)
            .padding(10)
            .glassEffect(.regular.interactive(), in: RoundedRectangle(cornerRadius: 16))
        }
        .buttonStyle(.plain)
    }
}

// MARK: - From Submissions/deedscan/DeedScanListingExperience.swift

//  DeedScanListingExperience.swift
//  ReactivChallengeKit
//
//  DeedScan — View Property. Scan the yard sign QR to instantly view listing details.
//  No download, no account needed.

import SwiftUI
import UIKit
import UserNotifications

struct DeedScanListingExperience: ClipExperience {
    static let urlPattern = "deedscan.app/clip"
    static let clipName = "DeedScan — View Property"
    static let clipDescription = "Scan the yard sign QR to instantly view listing details, price, and neighbourhood info — no download, no account needed"
    static let teamName = "DeedScan"
    static let touchpoint: JourneyTouchpoint = JourneyTouchpoint(
        id: "yard-sign",
        title: "Yard Sign",
        icon: "mappin.and.ellipse",
        context: "Physical QR code on for-sale yard sign",
        notificationHint: "Use time-sensitive nudges while context is fresh.",
        sortOrder: 30
    )
    static let invocationSource: InvocationSource = .qrCode

    let context: ClipContext

    // Hardcoded demo listing (matches live DB seed)
    private static let title = "Detached Family Home in North York"
    private static let address = "1250 Sheppard Ave W, Toronto, ON"
    private static let priceFormatted = "$1,499,000 CAD"
    private static let agentSavings = "~$74,950"
    private static let savingsLabel = "💰 Saves \(agentSavings) vs. agent commission"
    private static let bedrooms = 4
    private static let bathrooms = 3
    private static let sqft = 2400
    private static let aiScore = 91
    private static let aiLabel = "🛡️ \(aiScore)/100 Verified — No fraud signals"
    private static let sellerName = "Amelia Chen"
    private static let photo1 = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80"
    private static let photo2 = "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80"
    private static let neighbourhoodSummary = "8 min to Sheppard-Yonge · Loblaws 5 min walk · Earl Haig SS 0.6km"

    /// Price drop: $5,000 off → $1,494,000
    private static let newPriceFormatted = "$1,494,000 CAD"

    /// Only schedule the price-drop notification once per app session.
    private static var hasScheduledPriceDrop = false
    /// When we scheduled it; used to show reduced price only after user returns 3+ s later (notification fired).
    private static var priceDropScheduledAt: Date?

    @State private var showNeighbourhoodSheet = false
    @State private var priceDropApplied = false

    var body: some View {
        ZStack {
            ClipBackground()

            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    // 1. Photo carousel
                    photoCarousel

                    // 2. Title + address
                    VStack(alignment: .leading, spacing: 6) {
                        Text(Self.title)
                            .font(.system(size: 20, weight: .bold))
                            .foregroundStyle(.primary)
                        Text("📍 " + Self.address)
                            .font(.system(size: 14))
                            .foregroundStyle(.secondary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.horizontal, 16)

                    // 3. Price block (strikethrough + new price when price drop applied, once only)
                    VStack(alignment: .leading, spacing: 10) {
                        if priceDropApplied {
                            HStack(alignment: .firstTextBaseline, spacing: 10) {
                                Text(Self.priceFormatted)
                                    .font(.system(size: 22, weight: .semibold))
                                    .foregroundStyle(.secondary)
                                    .strikethrough(true, color: .secondary)
                                Text(Self.newPriceFormatted)
                                    .font(.system(size: 26, weight: .bold))
                                    .foregroundStyle(.primary)
                            }
                            Text("Price reduced by $5,000")
                                .font(.system(size: 14, weight: .medium))
                                .foregroundStyle(.white)
                                .padding(.horizontal, 14)
                                .padding(.vertical, 8)
                                .background(Color.blue, in: Capsule())
                        } else {
                            Text(Self.priceFormatted)
                                .font(.system(size: 26, weight: .bold))
                                .foregroundStyle(.primary)
                            Text(Self.savingsLabel)
                                .font(.system(size: 14, weight: .medium))
                                .foregroundStyle(.white)
                                .padding(.horizontal, 14)
                                .padding(.vertical, 8)
                                .background(Color.green, in: Capsule())
                        }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.horizontal, 16)

                    // 4. Specs row (scrollable so all chips visible on narrow screens)
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 12) {
                            specChip("🛏 \(Self.bedrooms) beds")
                            specChip("🚿 \(Self.bathrooms) baths")
                            specChip("📐 \(Self.sqft) sq ft")
                            specChip("0% Commission")
                        }
                    }
                    .padding(.horizontal, 16)

                    // 5. AI Fraud Score badge
                    Text(Self.aiLabel)
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundStyle(.white)
                        .padding(.horizontal, 14)
                        .padding(.vertical, 10)
                        .background(Color.green, in: RoundedRectangle(cornerRadius: 12))
                        .padding(.horizontal, 16)

                    // 5b. Price drop alert cue
                    HStack(spacing: 6) {
                        Image(systemName: "bell.fill")
                            .foregroundStyle(.blue)
                            .font(.caption)
                        Text("You'll get a price drop alert if this listing changes")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    .padding(.vertical, 6)
                    .padding(.horizontal, 16)

                    // 6. Neighbourhood Snapshot
                    VStack(alignment: .leading, spacing: 10) {
                        Text("📍 Neighbourhood Snapshot")
                            .font(.system(size: 16, weight: .bold))
                            .foregroundStyle(.primary)
                        Text(Self.neighbourhoodSummary)
                            .font(.system(size: 14))
                            .foregroundStyle(.secondary)
                        Button {
                            showNeighbourhoodSheet = true
                        } label: {
                            HStack(spacing: 4) {
                                Text("See more")
                                Image(systemName: "arrow.right")
                                    .font(.system(size: 12, weight: .semibold))
                            }
                            .font(.system(size: 15, weight: .medium))
                            .foregroundStyle(.blue)
                        }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.horizontal, 16)

                    // 7. Message Seller CTA
                    Button {
                        if let url = URL(string: "http://localhost:3000/messages?listingId=demo_listing_001&sellerId=demo_seller_001") {
                            UIApplication.shared.open(url)
                        }
                    } label: {
                        HStack(spacing: 10) {
                            Text("💬")
                            Text("Message Seller")
                                .font(.system(size: 17, weight: .semibold))
                        }
                        .foregroundStyle(.white)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 16)
                        .background(Color.blue, in: RoundedRectangle(cornerRadius: 16))
                    }
                    .buttonStyle(.plain)
                    .padding(.horizontal, 16)
                    .padding(.top, 8)
                    .padding(.bottom, 32)
                }
            }
            .scrollIndicators(.hidden)
            .sheet(isPresented: $showNeighbourhoodSheet) {
                neighbourhoodSheet
            }
            .onReceive(NotificationCenter.default.publisher(for: UIApplication.willResignActiveNotification)) { _ in
                Self.schedulePriceDropNotificationIfNeeded(
                    listingId: "demo_listing_001",
                    listingTitle: Self.title
                )
            }
            .onReceive(NotificationCenter.default.publisher(for: UIApplication.willEnterForegroundNotification)) { _ in
                checkAndApplyPriceDrop()
            }
        }
    }

    /// When user returns 3+ seconds after we scheduled the notification, show the reduced price once (simulates tapping the notification).
    private func checkAndApplyPriceDrop() {
        guard let scheduledAt = Self.priceDropScheduledAt else { return }
        guard Date().timeIntervalSince(scheduledAt) >= 3 else { return }
        Self.priceDropScheduledAt = nil
        Task { @MainActor in
            withAnimation(.easeOut(duration: 0.35)) {
                priceDropApplied = true
            }
        }
    }

    /// Schedules a local "price drop" notification 3s after the user leaves. Only schedules once per app session.
    private static func schedulePriceDropNotificationIfNeeded(listingId: String, listingTitle: String) {
        guard !hasScheduledPriceDrop else { return }

        let center = UNUserNotificationCenter.current()

        center.requestAuthorization(options: [.alert, .sound, .badge]) { granted, _ in
            guard granted else { return }

            hasScheduledPriceDrop = true
            priceDropScheduledAt = Date()

            let content = UNMutableNotificationContent()
            content.title = "🏠 Price Drop Alert"
            content.body = "\(listingTitle) — Seller just reduced the price by $5,000. Tap to view."
            content.sound = .default
            content.userInfo = ["url": "https://deedscan.app/clip?id=\(listingId)"]

            let trigger = UNTimeIntervalNotificationTrigger(timeInterval: 3, repeats: false)

            let request = UNNotificationRequest(
                identifier: "deedscan-pricedrop-\(listingId)",
                content: content,
                trigger: trigger
            )

            center.add(request) { error in
                if let error = error {
                    print("DeedScan notification error: \(error)")
                }
            }
        }
    }

    private func carouselImage(urlString: String, tag: Int) -> some View {
        AsyncImage(url: URL(string: urlString)) { phase in
            switch phase {
            case .success(let image):
                image
                    .resizable()
                    .scaledToFill()
            case .failure:
                Color(.tertiarySystemFill)
            default:
                ProgressView()
            }
        }
        .frame(height: 220)
        .clipped()
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .tag(tag)
    }

    private var photoCarousel: some View {
        TabView {
            carouselImage(urlString: Self.photo1, tag: 0)
            carouselImage(urlString: Self.photo2, tag: 1)
        }
        .tabViewStyle(.page)
        .frame(height: 220)
        .padding(.horizontal, 16)
    }

    private func specChip(_ text: String) -> some View {
        Text(text)
            .font(.system(size: 13, weight: .medium))
            .foregroundStyle(.secondary)
            .padding(.horizontal, 12)
            .padding(.vertical, 8)
            .background(Color(.tertiarySystemFill), in: Capsule())
    }

    private var neighbourhoodSheet: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    sectionBlock(title: "Transit") {
                        bullet("TTC Sheppard-Yonge Station — 8 min walk")
                        bullet("Bus 84 Sheppard — 2 min walk")
                    }
                    sectionBlock(title: "Groceries") {
                        bullet("Loblaws (Yonge & Sheppard) — 5 min walk")
                        bullet("Metro — 7 min walk")
                        bullet("FreshCo — 12 min drive")
                    }
                    sectionBlock(title: "Schools") {
                        bullet("Earl Haig Secondary School — 0.6 km")
                        bullet("Willowdale Middle School — 0.4 km")
                        bullet("Claude Watson School for the Arts — 1.1 km")
                    }
                }
                .padding(20)
            }
            .navigationTitle("Neighbourhood Snapshot")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") {
                        showNeighbourhoodSheet = false
                    }
                }
            }
        }
    }

    private func sectionBlock<Content: View>(title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.system(size: 16, weight: .bold))
                .foregroundStyle(.primary)
            VStack(alignment: .leading, spacing: 4) {
                content()
            }
        }
    }

    private func bullet(_ text: String) -> some View {
        HStack(alignment: .top, spacing: 8) {
            Text("•")
                .font(.system(size: 14))
                .foregroundStyle(.secondary)
            Text(text)
                .font(.system(size: 14))
                .foregroundStyle(.primary)
        }
    }
}

