//  SubmissionRegistry.swift
//  ReactivChallengeKit
//
//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved.
//

/// Auto-generated by scripts/generate-registry.sh — do not edit manually.
enum SubmissionRegistry {
    static let all: [any ClipExperience.Type] = [
        DeedScanClipExperience.self,
        DeedScanListingExperience.self,
    ]
}
